### ISSUE TITLE
v1.0.0 Checklist

### ISSUE THREAD

**Issue by ethanholz** [omsf-eco-infra/start-aws-gha-runner#1]
- [x] Rewrite Dockerfile to remove Alpine dependency (we won't need this once `gha-runner` is on PyPI)
- [x] Add GitHub Actions for coverage testing
    - [ ] We will need to add a CodeCov token for the repo @dwhswenson 
- [x] Publish to GitHub Marketplace
